Feature/ui fixes
confirmbiosciences/confirm-biosciences pull request #169
Opened 2020-10-19 00:05 UTC by MoiOcanas

2020-10-20 20:25 UTC, eduardorr97 commented on web/src/components/Layout/components/Header/components/OptionDropdownCollection/OptionDropdownCollection.tsx
> +                  </Link>
Here you want to validate wheter `service.text` & `service.href` exists or not and then render the Link or nothing

2020-10-20 20:26 UTC, eduardorr97 commented on web/src/components/Layout/components/Header/components/OptionDropdownCollection/OptionDropdownCollection.tsx
> +      ) : <></> }
I always recommend that if you dont have a default case, use `&&` operator instead of `?` (ternary) operator, that way we get the same result but with less code :)

2020-10-20 20:30 UTC, eduardorr97 commented on web/src/components/Layout/components/Header/components/OptionDropdownItems/OptionDropdownItems.tsx
> +            <div>
Do we really neeed this `<div>`?

2020-10-20 20:45 UTC, eduardorr97 commented on web/src/components/products/ProductActions/components/BulkOrderingForm/BulkOrderingForm.module.scss
> +
Im seeing this repeated all over, can we make it a sass mixin and just include it in a class?
```
//in a global file
@mixin invisibleLabel {
  ...
}

// in the modules that use it
.formLabel {
   @include invisibleLabel
}
```

2020-10-20 20:50 UTC, eduardorr97 commented on web/src/utils/globalTypes.ts
> +  services: Service[]
remember this can be undefined so better make it opcional with `?`

2020-10-20 20:52 UTC, MoiOcanas commented on web/src/components/products/ProductActions/components/BulkOrderingForm/BulkOrderingForm.module.scss
> +
I can actually do that for this and maybe other classes what I'm using on Cards

2020-10-20 21:09 UTC, eduardorr97 commented on web/src/components/products/ProductActions/components/BulkOrderingForm/BulkOrderingForm.module.scss
> +
awesome, go ahead

2020-10-21 22:30 UTC, diveddie requested changes
See comments for changes

2020-10-21 22:37 UTC, merged